from pathlib import Path
path = Path(r'D:\ai-theme-map-site\index.html')
text = path.read_text(encoding='utf-8')

insert_helpers_after = "        function normalizeRepository(rawRepo) {\n            if (!rawRepo || typeof rawRepo !== 'object') return {};\n\n            const normalized = {};\n            for (const [key, value] of Object.entries(rawRepo)) {\n                if (isValidMapData(value)) {\n                    normalized[key] = value;\n                }\n            }\n\n            if (Object.keys(normalized).length === 0 && isValidMapData(rawRepo)) {\n                normalized['map_default'] = rawRepo;\n            }\n\n            return normalized;\n        }\n"
helpers = insert_helpers_after + "\n        function stockCode(stock) {\n            if (!stock || typeof stock !== 'object') return '--';\n            return stock.ticker || stock.symbol || stock.code || stock.stock_code || '--';\n        }\n\n        function topRepresentativeStocks(mapData, limit = 6) {\n            const pool = Array.isArray(mapData?.stocks) ? mapData.stocks : [];\n            return pool\n                .slice()\n                .sort((a, b) => {\n                    const stageRank = x => benefitStageText(x) === '第一圈' ? 0 : benefitStageText(x) === '第二圈' ? 1 : 2;\n                    const scoreA = (stageRank(a) * -100) + (Number(a?.pureLevel || 0) * 10) + Number(a?.barrierLevel || 0);\n                    const scoreB = (stageRank(b) * -100) + (Number(b?.pureLevel || 0) * 10) + Number(b?.barrierLevel || 0);\n                    return scoreB - scoreA;\n                })\n                .slice(0, limit);\n        }\n\n        function evolutionSummary(mapData) {\n            return [\n                (mapData?.trigger_events || [])[0] || (mapData?.heat_drivers || [])[0] || '市場開始注意這個題材的起點',\n                (mapData?.heat_drivers || [])[1] || (mapData?.capital_flow || [])[0]?.stage || '資金與供應鏈開始擴散',\n                (mapData?.watch_signals || [])[0] || (mapData?.timeline_phases || [])[0]?.focus || '現在最該觀察的驗證訊號'\n            ].filter(Boolean).slice(0, 3);\n        }\n\n        function renderRepresentativeStocks(mapData) {\n            const container = document.getElementById('representative-stocks-container');\n            if (!container) return;\n            const picks = topRepresentativeStocks(mapData, 6);\n            container.innerHTML = picks.length\n                ? picks.map(stock => `\n                    <button onclick=\"openModal('${stock.id}')\" class=\"text-left rounded-2xl border border-emerald-800/30 bg-emerald-950/20 p-4 hover:border-emerald-600/50 transition\">\n                        <div class=\"flex items-center justify-between gap-3\">\n                            <div>\n                                <div class=\"text-sm font-bold text-emerald-200\">${stock.name}</div>\n                                <div class=\"text-[11px] font-mono text-emerald-400/80\">${stockCode(stock)}</div>\n                            </div>\n                            <div class=\"text-[11px] px-2 py-1 rounded-full border border-emerald-700/40 text-emerald-300\">${benefitStageText(stock)}</div>\n                        </div>\n                        <div class=\"mt-2 text-xs text-slate-300\">${stock.role || linkageRoleLabel(stock) || '代表股'}</div>\n                    </button>\n                `).join('')\n                : '<div class=\"text-slate-500 text-sm\">尚無代表股資料</div>';\n        }\n"
if insert_helpers_after in text and 'function stockCode(stock)' not in text:
    text = text.replace(insert_helpers_after, helpers)

text = text.replace("            const broadened = [];\n            keys.forEach(key => {\n                broadened.push({ key, mode: 'main' });\n                const related = mapsRepository[key]?.related_themes || [];\n                related.slice(0, 2).forEach((theme, idx) => {\n                    broadened.push({ key, mode: 'related', relatedTheme: theme, relatedIndex: idx });\n                });\n            });\n\n            broadened.forEach(entry => {\n                const map = mapsRepository[entry.key];\n                if (!map) return;\n                const isRelated = entry.mode === 'related';\n", "            keys.forEach(key => {\n                const map = mapsRepository[key];\n                if (!map) return;\n")

text = text.replace("                const card = document.createElement('div');\n                card.className = `bg-slate-900 border ${isRelated ? 'border-cyan-900/40' : 'border-slate-800'} rounded-2xl p-5 hover:border-slate-700 transition cursor-pointer flex flex-col justify-between shadow-lg hover:shadow-indigo-950/20`;\n                card.onclick = () => loadMapWorkspace(entry.key);\n                const title = isRelated ? `延伸主題：${entry.relatedTheme}` : map.title;\n                const subtitle = isRelated ? `源自主題：${map.title}` : `📅 發布時程: ${map.date}`;\n                const summary = isRelated ? `從「${map.title}」延伸追蹤的關聯題材，方便會員擴大觀察範圍。` : (map.desc || '');\n                const thesis = isRelated ? shortenText((map.watch_signals || [])[0] || (map.trigger_events || [])[0] || map.thesis || '', 52) : (map.thesis || '');\n                const tagText = isRelated ? `${entry.relatedTheme} · 延伸觀察` : (map.theme_tags || []).slice(0,3).join(' · ');\n", "                const card = document.createElement('div');\n                card.className = `bg-slate-900 border border-slate-800 rounded-2xl p-5 hover:border-slate-700 transition cursor-pointer flex flex-col justify-between shadow-lg hover:shadow-indigo-950/20`;\n                card.onclick = () => loadMapWorkspace(key);\n                const title = map.title;\n                const subtitle = `📅 發布時程: ${map.date}`;\n                const summary = map.desc || '';\n                const thesis = map.thesis || '';\n                const tagText = (map.theme_tags || []).slice(0,3).join(' · ');\n                const evo = evolutionSummary(map);\n                const reps = topRepresentativeStocks(map, 3);\n")

text = text.replace("                            <div class=\"bg-gradient-to-tr ${isRelated ? 'from-cyan-700 to-blue-600' : (map.color || 'from-indigo-500 to-cyan-500')} p-2 rounded-xl text-white shadow-md\">\n                                <i data-lucide=\"${isRelated ? 'sparkles' : (map.icon || 'layers')}\" class=\"w-5 h-5\"></i>\n", "                            <div class=\"bg-gradient-to-tr ${(map.color || 'from-indigo-500 to-cyan-500')} p-2 rounded-xl text-white shadow-md\">\n                                <i data-lucide=\"${map.icon || 'layers'}\" class=\"w-5 h-5\"></i>\n")

text = text.replace("                        <p class=\"text-xs text-slate-400 leading-relaxed line-clamp-3 mb-3 h-15\">${summary}</p>\n                        <p class=\"text-[11px] text-cyan-300/90 leading-relaxed line-clamp-2 mb-4\">${thesis}</p>\n", "                        <p class=\"text-xs text-slate-400 leading-relaxed line-clamp-3 mb-3 h-15\">${summary}</p>\n                        <p class=\"text-[11px] text-cyan-300/90 leading-relaxed line-clamp-2 mb-3\">${thesis}</p>\n                        <div class=\"rounded-xl border border-slate-800/70 bg-slate-950/40 p-3 mb-3\">\n                            <div class=\"text-[10px] uppercase tracking-[0.2em] text-slate-500 mb-2\">題材演變</div>\n                            <div class=\"space-y-1\">${evo.map(item => `<div class='text-[11px] text-slate-300'>• ${shortenText(item, 44)}</div>`).join('')}</div>\n                        </div>\n")

text = text.replace("                            <span class=\"text-red-400 bg-red-950/40 px-2 py-0.5 rounded-md border border-red-900/40 font-medium\">${isRelated ? '延伸主題' : map.heat}</span>\n                            <span class=\"text-amber-300 bg-amber-950/40 px-2 py-0.5 rounded-md border border-amber-900/40 font-medium\">${isRelated ? '關聯追蹤' : `火勢 ${map.heat_score ?? '--'}`}</span>\n", "                            <span class=\"text-red-400 bg-red-950/40 px-2 py-0.5 rounded-md border border-red-900/40 font-medium\">${map.heat}</span>\n                            <span class=\"text-amber-300 bg-amber-950/40 px-2 py-0.5 rounded-md border border-amber-900/40 font-medium\">火勢 ${map.heat_score ?? '--'}</span>\n")

text = text.replace("                        <div class=\"rounded-xl border border-emerald-800/30 bg-emerald-950/20 px-3 py-2\">\n                            <div class=\"text-[10px] uppercase tracking-[0.2em] text-emerald-400/80 mb-1\">優先關注</div>\n                            <div class=\"text-xs font-bold text-emerald-300 line-clamp-2\">${(map.stocks || []).slice(0, 3).map(s => s.name).join(' / ') || '待補'}</div>\n                        </div>\n", "                        <div class=\"rounded-xl border border-emerald-800/30 bg-emerald-950/20 px-3 py-2\">\n                            <div class=\"text-[10px] uppercase tracking-[0.2em] text-emerald-400/80 mb-1\">代表股</div>\n                            <div class=\"text-xs font-bold text-emerald-300 line-clamp-2\">${reps.map(s => `${s.name}(${stockCode(s)})`).join(' / ') || '待補'}</div>\n                        </div>\n")

text = text.replace("                        <span class=\"text-indigo-400 font-semibold hover:underline flex items-center gap-1\">探索核心架構 <i data-lucide=\"arrow-right\" class=\"w-3 h-3\"></i></span>\n", "                        <span class=\"text-indigo-400 font-semibold hover:underline flex items-center gap-1\">進入主題頁 <i data-lucide=\"arrow-right\" class=\"w-3 h-3\"></i></span>\n")

text = text.replace("            if (summaryEl) {\n                const summaryLines = [\n                    mapData.thesis || mapData.title || '尚無摘要',\n                    (mapData.trigger_events || [])[0] || (mapData.heat_drivers || [])[0] || '尚無驅動描述',\n                    (mapData.watch_signals || [])[0] || (mapData.related_themes || [])[0] || '尚無觀察重點'\n                ].filter(Boolean).slice(0, 3);\n                summaryEl.innerHTML = summaryLines.map(line => `<div class=\"rounded-xl border border-slate-800 bg-slate-950/50 px-3 py-2 text-xs text-slate-200 leading-5\">${shortenText(line, 60)}</div>`).join('');\n            }\n", "            if (summaryEl) {\n                const summaryLines = [\n                    `題材：${mapData.title || '尚無主題名稱'}`,\n                    `演變：${((mapData.trigger_events || [])[0] || (mapData.heat_drivers || [])[0] || '尚無演變說明')}`,\n                    `代表股：${topRepresentativeStocks(mapData, 3).map(s => `${s.name}(${stockCode(s)})`).join(' / ') || '尚無代表股'}`\n                ].filter(Boolean).slice(0, 3);\n                summaryEl.innerHTML = summaryLines.map(line => `<div class=\"rounded-xl border border-slate-800 bg-slate-950/50 px-3 py-2 text-xs text-slate-200 leading-5\">${shortenText(line, 90)}</div>`).join('');\n            }\n")

text = text.replace("                    <div class=\"space-y-3\">\n                        <div><div class=\"text-[11px] text-slate-500 mb-1\">主題 Thesis</div><div>${mapData.thesis || mapData.title || '尚無內容'}</div></div>\n                        <div><div class=\"text-[11px] text-slate-500 mb-1\">深度描述</div><div>${mapData.long_description || mapData.description || '尚無細節描述'}</div></div>\n                    </div>\n", "                    <div class=\"space-y-3\">\n                        <div><div class=\"text-[11px] text-slate-500 mb-1\">這是什麼題材</div><div>${mapData.thesis || mapData.title || '尚無內容'}</div></div>\n                        <div><div class=\"text-[11px] text-slate-500 mb-1\">它如何演變</div><div>${evolutionSummary(mapData).join(' → ')}</div></div>\n                        <div><div class=\"text-[11px] text-slate-500 mb-1\">代表股票</div><div>${topRepresentativeStocks(mapData, 5).map(s => `${s.name}(${stockCode(s)})`).join(' / ') || '尚無代表股'}</div></div>\n                    </div>\n")

for old, new in [
    ("${stock.name} (${stock.code})", "${stock.name} (${stockCode(stock)})"),
    ("${stock.name} <span class=\"text-[11px] text-indigo-400 font-mono\">${stock.code}</span>", "${stock.name} <span class=\"text-[11px] text-indigo-400 font-mono\">${stockCode(stock)}</span>"),
    ("stock.name + stock.code + stock.role + stock.sector", "stock.name + stockCode(stock) + stock.role + stock.sector"),
    ("[${stock.code}]", "[${stockCode(stock)}]"),
    ("(${stock.code})", "(${stockCode(stock)})"),
    ("${stock.name} <span class=\"text-sm text-slate-400 font-mono\">${stock.code}</span>", "${stock.name} <span class=\"text-sm text-slate-400 font-mono\">${stockCode(stock)}</span>")
]:
    text = text.replace(old, new)

path.write_text(text, encoding='utf-8')
print('done')
